name: Validate
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  html-validity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install W3C Validator
        run: npm install -g w3c-html-validator

      - name: Validate HTML
        run: npx html-validator index.html

  a11y:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install Axe CLI
        run: npm install -g @axe-core/cli

      - name: Install Headless Chrome
        run: npx browser-driver-manager install chrome

      - name: Validate A11y
        run: axe file://$(realpath index.html)
